### ISSUE TITLE
MapFrom expressions in to child collections need explicit null conversions but didn't in previous versions

### ISSUE THREAD

**Issue by TehWardy** [AutoMapper/AutoMapper#1604]
Hi guys, 

This is really annoying and it would be interesting to know how you ended up making this decision or if this is a bug or something ...

so I have a mapping for a decimal property on one of my objects ...

```
CreateMap<T1, T2>()
   .ForMember(c => c.SelectionTotal, opts => opts.MapFrom(acc => acc.Invoices.Where(i => i.SaleSelected).Sum(i => i.SaleValue)))
```
... It used to work fine, until I upgraded my automapper to v5 via nuget now I have to do this ...
```
CreateMap<T1, T2>()
  .ForMember(c => c.SelectionTotal, opts => opts.MapFrom(acc => acc.Invoices.Any(i => i.SaleSelected) ? acc.Invoices.Where(i => i.SaleSelected).Sum(i => i.SaleValue) : 0m))
```

WTF guys?
All this appears to do is make more of a mess of my code and break all my existing profiles because I have hundreds of instances of this all over my profiles.

At the very least allow me to use coallese or something so I don't have to repeat myself.

**Comment by JobQDelft** [comment]
I have exact the same issue.
I have a mapping like this:
`AutoMapper.Mapper.Initialize(cfg => cfg.CreateMap<Model1, Model4>().ForMember(t => t.Names, opt => opt.MapFrom(s => s.Model2.Names.Select(n => n.Name))));`

Model2 is null on my source, which was no problem in v4, it just returned null. Now I get a null reference exception in v5? This breaks my code. Do I need to change all my mappings to account for null reference exceptions or have I hit a bug?
Please advise what to do next.

**Comment by jbogard** [comment]
Try the MyGet build, does that work?

**Comment by JobQDelft** [comment]
I'm a little new here, can you help me with what the MyGet build is and where to get it?

**Comment by TehWardy** [comment]
@jbogard that's not my problem here by the way ... the title has changed the problem in to something else. 

The error I get is something like "cannot put nullable decimal in to decimal property" when before I could and it would implicitly cast that null to the default decimal value.
Because of the behaviour I tried to write this as less of a bug and more of a question as to weather this was a good thing as its a change in behaviour from previous versions.

It's not actually throwing a nullref it's throwing some linq related expression in an expression tree.

**Comment by jbogard** [comment]
I tried to change the title to describe the problem, "mappings seem to break" is not descriptive. There's also no exception message, making it quite a bit harder to debug this. I just get "wtf guys". Not helpful.

The MyGet URL is in the readme:

http://myget.org/gallery/automapperdev

**Comment by TehWardy** [comment]
I thought it might be enough to just give you the example of a mapping and the change I had to make to fix it. 
You should have enough information to reproduce the problem at least.
Also I would rather not put a beta build in my production codebase if you don't mind.

The property is nothing special it's just a normal non nullable property on my dto, as I said mapping in this situation used to work in v4.x now in the latest v5 build on nuget it doesn't without the additional null check ... I presume it has something to do with type safety or similar checks in the expression tree building code. 

I'd like to help but right now I'm so snowed under with my projects I thought at least if you had visibility of this it would be a start!

**Comment by JobQDelft** [comment]
I used the MyGet version to test the 5.1.0 alpha version and my null reference exception problem is solved in that version. Thank you for your help. Any idea when the 5.1.0 version will be ready to go live?

**Comment by jbogard** [comment]
@TehWardy I can't execute a configuration, at the least I need source/destination types too. I also don't want to spend time trying to figure out a repro if it's already fixed, that's maddening. That's why the MyGet feed exists, to verify that the fix is there. But it sounds like @JobQDelft verified it, so I'm closing.

**Comment by TehWardy** [comment]
:( the problem I have isn't null refs ... its a mapping issue binding to non nullable properties where the mapping expression could evaluate to null (validly) ... the problem it seems is that I have to repeat myself because I can't use a coalese

**Comment by jbogard** [comment]
Without any way to reproduce it (I have no way to reproduce a MapFrom by itself), no source/destination types, and others saying it's fixed in the latest...I really have nowhere to go from here.

Unless you've tried the latest and it's still failing for you, I don't like to leave open issues that myself nor any of the other contributors can reproduce.
