### ISSUE TITLE
Problem with ObjectContext?

### ISSUE THREAD

**Issue by foobarred1** [AutoMapper/AutoMapper#1881]
Using EF6.0 with ObjectContext:

Seems like I get the following error when mapping from a DTO (with a collection) to an EF6 object.

{"The EntityCollection has already been initialized. The InitializeRelatedCollection method should only be called to initialize a new EntityCollection during deserialization of an object graph."}

I do not get an error when using DBContext.

Code snippet:

```
Imports AutoMapper
Imports AutoMapper.Mappers
Public Class QuoteModel
    Public Property ID As Integer
    Public Property Quote_Lines As List(Of Quote_LinesDTO)
    Public Sub New()
        Me.Quote_Lines = New List(Of Quote_LinesDTO)
    End Sub
End Class
Public Class Quote_LinesDTO
    Public Property ID As Integer
    Public Property Line_ID As Integer
    Public Property Date_Created As DateTime
    Public Property User_Created_ID As Guid
    Public Property GlobalID As Guid

End Class

Public Class Form1

    Private Sub Button1_Click(sender As Object, e As EventArgs) Handles Button1.Click
        Using theContext As New FleetFusionEntities
            Dim theQuote As Quote = theContext.Quotes.Where(Function(ent) ent.ID = 151709).SingleOrDefault

            Dim theQuoteModel As New QuoteModel
            theQuoteModel.ID = 151709
            theQuoteModel.Quote_Lines.Add(New Quote_LinesDTO With {.Line_ID = 6, .Date_Created = Now, .GlobalID = Guid.NewGuid, .User_Created_ID = Guid.NewGuid})


            Dim MapConfig As New AutoMapper.MapperConfiguration(Sub(cfg)
                                                                    cfg.AddProfile(Of Automapper_Profile)()
                                                                End Sub)
            Dim Mapper As AutoMapper.IMapper = New AutoMapper.Mapper(MapConfig)

            Mapper.Map(theQuoteModel, theQuote)

        End Using
    End Sub
End Class

Public Class Automapper_Profile
    Inherits AutoMapper.Profile
    Public Sub New()
        CreateMap(Of QuoteModel, Quote)()
        CreateMap(Of Quote_LinesDTO, Quote_Lines)()
    End Sub
End Class
`
```

**Comment by jbogard** [comment]
It looks like you're reverse mapping into a live EF entity. Here There Be Dragons. By default, AutoMapper will replace all destination members - including collections. What do you want to happen with the Quote_Lines property?

**Comment by foobarred1** [comment]
Actually, I plan on using Automapper.Collection and Automapper.Collection.EntityFramework to handle the collections so that it will add/update/replace based on ID.  However, I got this issue.  I decided to strip out all the code related to the Collection namespace and try again and still ran into this error message.

The only way I got this working is through DBcontext, and wasn't sure if it was a bug in Automapper, or whether there was something wrong with my implementation.

**Comment by TylerCarlson1** [comment]
This might be related to #1866.

For explicit maps you'll have to make the mapper twice.  Once to make the map so the EF convention can map based on ID, and then a second time to use those maps to make the list update by ID correctly.

If you can use a convention then you don't have to make the mapper twice.

**Comment by foobarred1** [comment]
I'm not sure if I understand.  Is the Error:  "The EntityCollection has already been initialized..."  related to the fact that I'm NOT using Automapper.Collection in my code snippet?

Or rather related to my implementation of the Automapper.Profile?

If so, why would I not get an error using DBContext?

**Comment by TylerCarlson1** [comment]
I think DbContext is it's own thing and doesn't have a relation to the entities, so there's no way it will get the exception.  Where as FleetFusionEntities knows about the EF objects, so its model checks for those things.  Never used DbContext all by itself, but I bet it doesn't do anything, since you need to inherit from it to do anything in EF.

Alternatively what you can try is just get AM.Collections and call `EqualityComparison` for Quote_LinesDTO that way you know for sure the collection mapping will work.  That should fix the exception and then that means that you have the profile configuration problem.

**Comment by foobarred1** [comment]
So, the bottom line is that ObjectContext should work as long as I implement automapper and automapper.collection properly.  Correct?

**Comment by foobarred1** [comment]
Okay.  I've added AM.Collection and such, and I still get the same error.

`Imports AutoMapper
Imports AutoMapper.Mappers
Imports AutoMapper.Collection
Imports AutoMapper.EntityFramework
Imports AutoMapper.EquivilencyExpression

Public Class QuoteModel
    Public Property ID As Integer
    Public Property Quote_Lines As List(Of Quote_LinesDTO)
    Public Sub New()
        Me.Quote_Lines = New List(Of Quote_LinesDTO)
    End Sub
End Class
Public Class Quote_LinesDTO
    Public Property ID As Integer
    Public Property Line_ID As Integer
    Public Property Date_Created As DateTime
    Public Property User_Created_ID As Guid
    Public Property GlobalID As Guid

End Class

Public Class Form1

    Private Sub Button1_Click(sender As Object, e As EventArgs) Handles Button1.Click
        Using theContext As New FleetFusionEntities
            Dim theQuote As Quote = theContext.Quotes.Where(Function(ent) ent.ID = 151709).SingleOrDefault
            Dim theQuoteModel As New QuoteModel
            theQuoteModel.ID = 151709
            theQuoteModel.Quote_Lines.Add(New Quote_LinesDTO With {.ID = 5, .Line_ID = 6, .Date_Created = Now, .GlobalID = Guid.NewGuid, .User_Created_ID = Guid.NewGuid})


            Dim MapConfig As New AutoMapper.MapperConfiguration(Sub(cfg)
                                                                    cfg.AddProfile(Of CollectionProfile)()
                                                                    cfg.AddProfile(Of Automapper_Profile)()
                                                                End Sub)
            Dim Mapper As AutoMapper.IMapper = New AutoMapper.Mapper(MapConfig)

            Mapper.Map(theQuoteModel, theQuote)
            'theContext.SaveChanges()
        End Using
    End Sub
End Class

Public Class Automapper_Profile
    Inherits AutoMapper.Profile
    Public Sub New()
        CreateMap(Of QuoteModel, Quote)()
        CreateMap(Of Quote_LinesDTO, Quote_Lines).EqualityComparision(Function(dto, ent) dto.ID = ent.ID)
    End Sub
End Class`

**Comment by TylerCarlson1** [comment]
Weird.  Got a few ideas to try.

Can you try making a reverse map of Quote_Lines and doing the equality comparison on that.  It might be a little backwards in how it works.

If that doesn't work, if you ignore the collection property does that cause the exception to occur?  Just want to know for sure it's just AM.

What version of EF is this?  EF 6.1.3 is the latest and AM.Collection.EF will use this.  I don't know if you got this far.  Maybe the version might cause a problem perhaps?

Last possible idea is it has something to do with VB not compiling Function() call correctly.  Had an issue with this before, although I don't know all the details on the top of my head.

**Comment by foobarred1** [comment]
1.  I did a reverse map and no change.
2.  I commented out the collection property and I did not get an error.
3.  I am using EF 6.1.3 so that's not the issue.
4.  Which function call are you referring to?  I'm assuming the lambda call concerning the equivalency.

I still believe that this is a problem with Automapper & ObjectContext, not Automapper.Collection.  My original post stripped out all reference to Automapper.Collection, and it returned that error.

**Comment by TylerCarlson1** [comment]
you did the reverse map and did EqualityComparison function on it as well?

Also what do you mean ObjectContext vs DbContext.  What is FleetFusionEntities inheriting from?

**Comment by foobarred1** [comment]
If I understand correctly, Yes:

CreateMap(Of Quote_Lines, Quote_LinesDTO).EqualityComparision(Function(ent, dto) ent.ID = dto.ID)

ObjectContext was used prior to EF4.1, which was when I created all my DAL libraries.  EF4.1+ uses DBContext, which is simply a wrapper around ObjectContext.

The main differences as far as we're concerned is that ObjectContext has a different template generation:

![image](https://cloud.githubusercontent.com/assets/24896875/21620654/0064e0d6-d1bb-11e6-8530-0d8feaaf60ed.png)

I've tried the code with using DBContext (which is default for EF6) and the code works without error.  Automapper.Collection works as advertised.  So I believe that it's an issue with the way Automapper handles collections vis-a-vis ObjectContext.

**Comment by TylerCarlson1** [comment]
Oh OK I gotcha now.  My guess is that with ObjectContext it's not auto-generating the list of Quote_Lines's and even with AM.Collection it will see there's no list and make and set one, and that will cause the problems.

Or the Quote_Line's property is some weird collection type that doesn't inherit from `ICollection<>` and AM tries to create a new instance of it, because it won't try to map a collection if it doesn't recognize ICollection interface.

**Comment by foobarred1** [comment]
Quote_Lines is nothing special.

![image](https://cloud.githubusercontent.com/assets/24896875/21621058/02754954-d1bd-11e6-9a4d-00c8c3e231dc.png)

So, if it is a problem with Automapper/Objectcontext, is it something that will be fixed?  I don't want to change all my libraries if I don't have to, especially given that DBContext really doesn't offer me any technical advantage over ObjectContext.

**Comment by TylerCarlson1** [comment]
I meant the actual code and debugging.  The relationship's navigation property, what type is it, does that type inherit from ICollection?  And in debugging is it null for any reason?

**Comment by lbargaoanu** [comment]
@foobarred1 If you can isolate things and repro something without EF, that would certainly make the issue more clear.

**Comment by foobarred1** [comment]
@lbargaoanu  EF/ObjectContext is the whole issue so reproducing it without EF would be meaningless.

![image](https://cloud.githubusercontent.com/assets/24896875/21621415/7c9e3d66-d1be-11e6-8924-f2b19fe249fe.png)

as you can see the collection is not null (I do not believe it can ever be null as a 1 to many entity collection) and it is of type EntityCollection which does implement the ICollection(of TEntity) interface.  https://msdn.microsoft.com/en-us/library/bb354106(v=vs.110).aspx

**Comment by TylerCarlson1** [comment]
The problem is probably the fact that regardless of what AM does it will call the setter of the property.  Even if it's the same EntityCollection being set, the fact you are trying to set it causes the exception to be thrown.  I don't think there's a workaround in any version for this.

AM would have to be re-written to not allow setters to be called if re-using the same collection.

**Comment by lbargaoanu** [comment]
AM just maps objects, doesn't know anything about EF. It's on you to find out what AM does that breaks your app.

**Comment by foobarred1** [comment]
Thanks for your help.  At least I know that I either have to switch to DBContext or not use Automapper when mapping to an EF Entity.

**Comment by lbargaoanu** [comment]
If a destination is passed, for an inner object, the destination inner object is used and the property is not assigned. I think it would make sense for collections to behave the same. I don't know if there is a test that expects a new collection.

**Comment by lbargaoanu** [comment]
And it does exactly that, it reuses the destination collection. It's smth else.

**Comment by TylerCarlson1** [comment]
Yes it re-uses the collection.  But it still sets the property regardless.  Same for inner objects I believe.

It resolves every value (uses the destination in this case) then sets the property to the resolved value always.
But if the resolved value is the destination it will still set it back, in theory overwriting itself.  And that overwrite mechanism is what causes the exception in this case.

**Comment by TylerCarlson1** [comment]
Ergo if you run `theQuote.Quote_Lines = theQuote.Quote_Lines` the same exception would occur.

**Comment by lbargaoanu** [comment]
Aha. I guess we could try and fix that.

**Comment by lbargaoanu** [comment]
I don't think it's worth doing it inside AM. It should be worked around by omitting the setter or by checking for the same value.
