### ISSUE TITLE
Mapping of Expression<Func<T,bool>> causes exception starting from AutoMapper 5.2.0

### ISSUE THREAD

**Issue by vukispasic** [AutoMapper/AutoMapper#1886]
Starting from AutoMapper version 5.2.0 we can't execute mapped queries anymore. Exception is "Additional information: variable 'r' of type 'OmmitedDTOModel3.EntityDTO1' referenced from scope '', but it is not defined". In production code we are using EF so execution of EF query results in exception "The parameter 'r' was not bound in the specified LINQ to Entities query expression". AutoMapper 5.1.1 works fine, as well as versions 4

I made a repro:
https://github.com/vukispasic/AutoMapperExpressionMappingIssue.

**Comment by TylerCarlson1** [comment]
Can you try the [MyGet Build](https://github.com/AutoMapper/AutoMapper/wiki/The-MyGet-build)?

**Comment by vukasinspasic** [comment]
Already tried, same issue

**Comment by TylerCarlson1** [comment]
https://github.com/AutoMapper/AutoMapper/commit/b22ce56ac64a7a2d2ccd2ecb8ef69302c6cee63e#diff-51fc29521ce7d80eddd4a9ef366b9d09R300 Here's the problem most likely.  I'm guessing it needs to get replaced with IsAssignableFrom, because it only fails on Id in your repo, which is a property inherited from the base entity class.

**Comment by vukasinspasic** [comment]
Thank you

**Comment by vukispasic** [comment]
Hello. I fixed the issue as TylerCarlson1 proposed. I also created unit test. How can I publish from my local branch and make pull request? I get 403 (Forbidden). Thanks

**Comment by TylerCarlson1** [comment]
You have to fork the repository in github and push the branch there. Then from that remote branch you can request a PR on github

Sent from my iPhone

On Jan 14, 2017, at 1:32 PM, vukispasic <notifications@github.com<mailto:notifications@github.com>> wrote:


Hello. I fixed the issue as TylerCarlson1 proposed. I also created unit test. How can I publish from my local branch and make pull request? I get 403 (Forbidden). Thanks

-

**Comment by vukasinspasic** [comment]
I made pull request https://github.com/AutoMapper/AutoMapper/pull/1911 as instructed

**Comment by yasin-uohyd** [comment]
Hi @jbogard, when are we going to release in nuget.org

**Comment by cjrogala** [comment]
I see this marked as closed, but I am still seeing this behavior when I run a release build with the Optimize Code build configuration set to true.  Can you please confirm this is truly closed?  If so, I would recommend testing again with the Optimize Code option set to true.

**Comment by lbargaoanu** [comment]
@cjrogala A repro would help. Make a gist that we can execute and see fail.
