### ISSUE TITLE
Mapping Expressions with ICollection

### ISSUE THREAD

**Issue by zhylinsky** [AutoMapper/AutoMapper#648]
Hello, 
I have a problem with mapping expression with a collection. 
Expression: 
dealers = Find(d => d.Branches.Any(b => branchIds.Contains(b.Id)));

        public IList<TModel> Find(Expression<Func<TModel, bool>> filter, params Expression<Func<TModel, object>>[] includes)
        {
            IQueryable<TEntity> query = SomeDbContext.Set<TEntity>();
            if (filter != null)
            {
                query = query.Where(Mapper.Map<Expression<Func<TEntity, bool>>>(filter));
            }
            foreach (var include in includes)
            {
                query = query.Include(Mapper.Map<Expression<Func<TEntity, object>>>(include));
            }
            return Mapper.Map<IEnumerable<TModel>>(query).ToList();
        }

Exception:
Mapping types:
Expression`1 -> Expression`1
System.Linq.Expressions.Expression`1[[System.Func`2[[Supersite.Models.Dealer],[System.Boolean]]]] -> System.Linq.Expressions.Expression`1[[System.Func`2[[Supersite.Entities.Dealer],[System.Boolean]]]]

Destination path:
Expression`1

Source value:
d => d.Branches.Any(b => value(Supersite.Repositories.EF.DealerRepository+<>c__DisplayClass0).branchIds.Contains(b.Id)) ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at AutoMapper.Mappers.ExpressionMapper.MappingVisitor.VisitMember(MemberExpression node)
   at System.Linq.Expressions.MemberExpression.Accept(ExpressionVisitor visitor)
   at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)
   at System.Linq.Expressions.ExpressionVisitor.VisitMethodCall(MethodCallExpression node)
   at System.Linq.Expressions.MethodCallExpression.Accept(ExpressionVisitor visitor)
   at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)
   at System.Linq.Expressions.ExpressionVisitor.VisitLambda[T](Expression`1 node)
   at System.Linq.Expressions.Expression`1.Accept(ExpressionVisitor visitor)
   at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)
   at System.Linq.Expressions.ExpressionVisitor.VisitArguments(IArgumentProvider nodes)
   at System.Linq.Expressions.ExpressionVisitor.VisitMethodCall(MethodCallExpression node)
   at System.Linq.Expressions.MethodCallExpression.Accept(ExpressionVisitor visitor)
   at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)
   at AutoMapper.Mappers.ExpressionMapper.Map(ResolutionContext context, IMappingEngineRunner mapper)
   at AutoMapper.MappingEngine.AutoMapper.IMappingEngineRunner.Map(ResolutionContext context)
   --- End of inner exception stack trace ---
   at AutoMapper.MappingEngine.AutoMapper.IMappingEngineRunner.Map(ResolutionContext context)
   at AutoMapper.MappingEngine.MapCore(Object source, Type sourceType, Type destinationType, MappingOperationOptions options)
   at AutoMapper.MappingEngine.Map(Object source, Type sourceType, Type destinationType, Action`1 opts)
   at AutoMapper.MappingEngine.Map[TDestination](Object source, Action`1 opts)
   at AutoMapper.MappingEngine.Map[TDestination](Object source)
   at AutoMapper.Mapper.Map[TDestination](Object source)

**Comment by ronalds1** [comment]
@TylerCarlson1 ..  trying to debug your code but getting the null exception error on this:

private PropertyMap PropertyMap(MemberExpression node)
            {
                var memberAccessor = node.Member.ToMemberAccessor();
                var propertyMap = _typeMap.GetExistingPropertyMapFor(memberAccessor);  // --> _typeMap is null..   how to fix this ?
                return propertyMap;
            }

**Comment by TylerCarlson1** [comment]
From the looks of it there isn't an existing property map for that member accessor.  If you are using property p.Foo and explicitly ignore it or automapper can't figure it out by convention, then it would probably return a null type map.  I haven't accounted for that situation, but maybe it needs to be accounted for in the exception handling, so it's easier for the user to decipher what's going on.  Please check and if it's not the case, please elaborate on what exactly you are doing.

**Comment by ronalds1** [comment]
@TylerCarlson1     yes..  i;m using p.Foo but did not explicitly ignore in the mapping registration..   

please consider the following code:

    public interface ISomeType
    {
        string Description { get; }
        string Key { get; }
    }

    public interface IObject
    {
         ISomeType SomeType { get; set;}
    }


    public class ObjectDto : IObject
    {
         public  ISomeType SomeType { get; set;}
    }

    public class ObjectEntity : IObject
    {
         public ISomeType SomeType { get; set;}
    }

The mapping as follow:
            Mapper.CreateMap<Expression<Func<ObjectDto, bool>>, Expression<Func<ObjectEntity, bool>>>();
            Mapper.CreateMap<Expression<Expression<Func<ObjectEntity, bool>>>, Func<ObjectDto, bool>>();


The usage:

             var currentCount = this.repository.Find(_ => _.SomeType.Key == "SomeKey").Count();

The find method above having the following signature

        public IEnumerable<TDto> Find(Expression<Func<TDto, bool>> expression)
        {
            // Map our dto Expression to Entity Expression
            var entityExpression =
                Mapper.Map<Expression<Func<TDto, bool>>, Expression<Func<TEntity, bool>>>(expression);

       }

**Comment by TylerCarlson1** [comment]
Oh well it might have something to do with the fact that you are mapping using the same interface on both sides of the map.  It doesn't know how to map ISomeType to ISomeType, because unlike regular mappings, the expression has no way of knowing what the source and destination types are.  Like SomeType and SomeTypeDto, so it can't work unless you have a ISomeType to ISomeType mapper created I would imagine.

**Comment by ronalds1** [comment]
ok..  fair enough..  but i the error occurs as well on the DateTime property (below)

   public interface IObject
   {
        ISomeType SomeType { get; set;}
   }


   public class ObjectDto : IObject
   {
        public  ISomeType SomeType { get; set;}
        public DateTime Created { get; set;}
   }

   public class ObjectEntity : IObject
   {
        public ISomeType SomeType { get; set;}
        public DateTime Created { get; set;}
   }


The usage:
         var year = 2014;
         var currentCount = this.repository.Find(_ => _.Created.Year == year).Count();

**Comment by TylerCarlson1** [comment]
Ok I finally see what's going on.  I updated the PR with that fix and a unit test to go along with it.  Turns out I need to check to see if types are same and if so don't bother with any kind of conversion.

This should also mean you don't have to worry about ISomeType to ISomeType mapper being generated.

Thanks for the example.  I completely dismissed a very important scenario.

**Comment by ronalds1** [comment]
thanks../   another scenario which is also failing 

    var name = "John";
    var currentCount = this.repository.Find(_ => _.Name.Equals(name)).Count();

the above is throwing:

InvalidOperationException :   Operation is not valid due to the current state of the object.

**Comment by TylerCarlson1** [comment]
Updated PR fixed that scenarios.

**Comment by ronalds1** [comment]
thanks..  going back to the above "type" example..

this is now working (was not working before)

      var currentCount = this.repository.Find(_ => _.SomeType.Key == "SomeKey").Count();

the following is still throwing NullReferenceException

      string variableKey = "test";
      var currentCount = this.repository.Find(_ => _.SomeType.Key == variableKey).Count();

**Comment by TylerCarlson1** [comment]
I can't seem to replicate the null reference exception in unit tests.  Can you determine if it has something to do with SomeType having the same interface?  Or maybe you still have the ISomeType to ISomeType map existing still?

Anyways I need more information to isolate the scenario in order to replicate.

**Comment by ronalds1** [comment]
@jbogard @TylerCarlson1 ..  do you still have ETA of when #649 will be released ?

**Comment by TylerCarlson1** [comment]
Haven't heard anything from @jbogard about this issue yet.  Just patiently waiting for something to happen.

**Comment by TylerCarlson1** [comment]
Updated pull request again and fixed all failed cases I had.  I think the PR is ready to be accepted now.

**Comment by TylerCarlson1** [comment]
This one should be closed since #778 was merged and fixed this issue.

**Comment by jbogard** [comment]
Great, thanks!
